/**
 * generated by Xtext 2.22.0
 */
package com.coffee.hlvl.impl;

import com.coffee.hlvl.ExternalElement;
import com.coffee.hlvl.HlvlPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>External Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExternalElementImpl extends ReferencedElementImpl implements ExternalElement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExternalElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return HlvlPackage.Literals.EXTERNAL_ELEMENT;
  }

} //ExternalElementImpl
