/**
 * generated by Xtext 2.22.0
 */
package com.coffee.hlvl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>External Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.coffee.hlvl.HlvlPackage#getExternalElement()
 * @model
 * @generated
 */
public interface ExternalElement extends ReferencedElement
{
} // ExternalElement
