/**
 * generated by Xtext 2.22.0
 */
package com.coffee.hlvl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.coffee.hlvl.ModelRef#getImportURI <em>Import URI</em>}</li>
 * </ul>
 *
 * @see com.coffee.hlvl.HlvlPackage#getModelRef()
 * @model
 * @generated
 */
public interface ModelRef extends EObject
{
  /**
   * Returns the value of the '<em><b>Import URI</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Import URI</em>' reference.
   * @see #setImportURI(Model)
   * @see com.coffee.hlvl.HlvlPackage#getModelRef_ImportURI()
   * @model
   * @generated
   */
  Model getImportURI();

  /**
   * Sets the value of the '{@link com.coffee.hlvl.ModelRef#getImportURI <em>Import URI</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Import URI</em>' reference.
   * @see #getImportURI()
   * @generated
   */
  void setImportURI(Model value);

} // ModelRef
