/**
 * generated by Xtext 2.22.0
 */
package com.coffee.hlvl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Referenced Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.coffee.hlvl.HlvlPackage#getReferencedElement()
 * @model
 * @generated
 */
public interface ReferencedElement extends EObject
{
} // ReferencedElement
